version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bloc-notas-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./backend:/home/app
    links:
      - database
  database:
    image: mongo
    container_name: bloc-notas-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./database:/data/db
  express:
    image: mongo-express
    container_name: bloc-notas-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=database
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    restart: always
    depends_on: 
      - database
